# Generated by Django 4.2.2 on 2024-09-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_ethereum_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ethereum_wallet_address',
            field=models.CharField(default=1, max_length=42),
            preserve_default=False,
        ),
    ]
